"""Добавление стека технологий пользователей

Revision ID: 566c6f728fa7
Revises: 7c37dbeff975
Create Date: 2021-09-02 21:51:21.842548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566c6f728fa7'
down_revision = '7c37dbeff975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_stacks_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stacks'))
    )
    op.drop_column('groups', 'github_url')
    op.add_column('users', sa.Column('github', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stacks')
    # ### end Alembic commands ###
