"""Добавляем приглашения пользователей

Revision ID: 762864995031
Revises: 87a0c11cc68b
Create Date: 2021-10-06 21:19:52.285056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762864995031'
down_revision = '87a0c11cc68b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('_from', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['_from'], ['teams.id'], name=op.f('fk_user_notifications__from_teams')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_notifications'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_notifications')
    # ### end Alembic commands ###
