"""Изменение поля github_url в Users

Revision ID: 7e0271e12aa2
Revises: 566c6f728fa7
Create Date: 2021-09-03 19:10:28.671220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e0271e12aa2'
down_revision = '566c6f728fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github', sa.String(length=100), nullable=True))
    op.drop_column('users', 'github_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_url', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('users', 'github')
    # ### end Alembic commands ###
