"""Добавляем TeamNotifications

Revision ID: 87a0c11cc68b
Revises: 9fc7ff0a15ff
Create Date: 2021-09-27 11:29:11.550567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a0c11cc68b'
down_revision = '9fc7ff0a15ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('_from', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['_from'], ['users.id'], name=op.f('fk_team_notifications__from_users')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_notifications_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_notifications'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_notifications')
    # ### end Alembic commands ###
