"""Небольшие изменения в users и teams

Revision ID: 9fc7ff0a15ff
Revises: e0aa5cdbab22
Create Date: 2021-09-19 13:42:58.653858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc7ff0a15ff'
down_revision = 'e0aa5cdbab22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('product_type', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_column('teams', 'product_type')
    # ### end Alembic commands ###
