"""Изменяем названия и структуру бд

Revision ID: e0aa5cdbab22
Revises: 7e0271e12aa2
Create Date: 2021-09-15 20:53:05.618409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0aa5cdbab22'
down_revision = '7e0271e12aa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('descripton', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('github', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], name=op.f('fk_members_member_id_users')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_members_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_members'))
    )

    op.add_column('leaders', sa.Column('team_id', sa.Integer(), nullable=True))
    op.add_column('leaders', sa.Column('leader_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_leaders_user_id_users', 'leaders', type_='foreignkey')
    op.drop_constraint('fk_leaders_group_id_groups', 'leaders', type_='foreignkey')
    op.create_foreign_key(op.f('fk_leaders_leader_id_users'), 'leaders', 'users', ['leader_id'], ['id'])
    op.create_foreign_key(op.f('fk_leaders_team_id_teams'), 'leaders', 'teams', ['team_id'], ['id'])
    op.drop_column('leaders', 'group_id')
    op.drop_column('leaders', 'user_id')
    op.alter_column('stacks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'github',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_table('groups_combinations')
    op.drop_table('groups')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'github',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('stacks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('leaders', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('leaders', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_leaders_team_id_teams'), 'leaders', type_='foreignkey')
    op.drop_constraint(op.f('fk_leaders_leader_id_users'), 'leaders', type_='foreignkey')
    op.create_foreign_key('fk_leaders_group_id_groups', 'leaders', 'groups', ['group_id'], ['id'])
    op.create_foreign_key('fk_leaders_user_id_users', 'leaders', 'users', ['user_id'], ['id'])
    op.drop_column('leaders', 'leader_id')
    op.drop_column('leaders', 'team_id')
    op.create_table('groups',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('groups_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('descripton', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('github', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_groups'),
    postgresql_ignore_search_path=False
    )
    op.create_table('groups_combinations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='fk_groups_combinations_group_id_groups'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_groups_combinations_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_groups_combinations')
    )
    op.drop_table('members')
    op.drop_table('teams')
    # ### end Alembic commands ###
